<?php

namespace App\Console\Commands;

use App\Models\Employee;
use App\Models\Attendance;
use Carbon\Carbon;
use Illuminate\Console\Command;

class AutoGenerateDailyAttendance extends Command
{
    protected $signature = 'attendance:auto-generate {date?}';
    protected $description = 'Generate draft absensi harian karyawan sesuai shift posisi (Default: Hari Ini)';

    public function handle(): int
    {
        // Jika argumen date diisi (misal: php artisan attendance:auto-generate 2026-08-18), gunakan itu. Jika tidak, pakai hari ini.
        $targetDate = $this->argument('date') 
            ? Carbon::parse($this->argument('date'))->toDateString() 
            : Carbon::today()->toDateString();

        $this->info("Memproses auto-generate absensi untuk tanggal: {$targetDate}");

        // 1. Ambil karyawan aktif yang memiliki posisi dan shift
        $employees = Employee::with('position.shift')
            ->where('is_active', true)
            ->whereHas('position', function ($query) {
                $query->whereNotNull('shift_id');
            })
            ->get();

        $insertedCount = 0;
        $skippedCount  = 0;

        foreach ($employees as $employee) {
            $shift = $employee->position?->shift;

            if (!$shift) {
                continue;
            }

            // 2. Gunakan firstOrCreate agar tidak duplikat jika record sudah ada
            $attendance = Attendance::firstOrCreate(
                [
                    'employee_id' => $employee->id,
                    'date'        => $targetDate,
                ],
                [
                    'clock_in'  => $shift->clock_in,
                    'clock_out' => $shift->clock_out,
                    'status'    => 'Hadir', // Atau set 'Draft' / 'Jadwal' sesuai standar sistem agan
                ]
            );

            if ($attendance->wasRecentlyCreated) {
                $insertedCount++;
            } else {
                $skippedCount++;
            }
        }

        $this->info("Selesai! {$insertedCount} data absensi berhasil dibuat, {$skippedCount} data sudah ada sebelumnya.");

        return Command::SUCCESS;
    }
}